# -*- coding: utf-8 -*-
"""numpy_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5hyBxY8aNtc8fvSvc1klPwgtkvb9sdd
"""

import numpy as np
l =[1,2,3,6,7]
npl = np.array(l)
npl

npl.shape

npl

np2 = np.array([npl])
np2

np2.shape

np3 = np.array([np2])
np3

np3.ndim

np4 = np.array([np3])
np4

np4.ndim

n = np.array([(1,2,7,9),
             (3,4,8,9),
             (6,7,8,5)])
n

n.ndim

n3=np.array([[(1,2,3,4),
              (3,4,5,6),
              (7,8,9,1)]])

n3.ndim

np.zeros(5)

np.ones(5)

# dot product
a = [2,4]
b = [5,6]
a1 = np.array(a)
b1 = np.array(b)
a1+b1

a1*b1

vijay = np.dot(a1,b1)
print(vijay)

l = [1,3.5,bool,'vijay',1+2j]
len(l)

type(l)



